version: '3'
services:
    app:
        build: .
        command: node build/main.js
        restart: always
        env_file:
            - .env
        environment:
            - BOT_TOKEN=${BOT_TOKEN}
            - NODE_ENV=${NODE_ENV}
